const DataGoods = [{
  "id":"001",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"002",
  "name": "简约风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "否",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"003",
  "name": "欧美风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"004",
  "name": "北欧风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "不包邮",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"005",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"006",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "否",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"007",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "否",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"008",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"009",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"010",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"011",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"012",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "否",
  "listing_time": "2024-01-03",
},
{
  "id":"013",
  "name": "简约风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "是",
  "listing_time": "2024-01-03",
},
{
  "id":"014",
  "name": "简约风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "是",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "是",
  "listing_time": "2024-01-03",
},
{
  "id":"015",
  "name": "现代风格 时尚舒适 科技布沙发",
  "model":"乳胶枕*1",
  "classify": "枕头/枕芯",
  "style": "现代",
  "volume": "1.00",
  "free": "否",
  "supply_price": "88",
  "sales_price": "398.0",
  "store_retail_price": "264",
  "profit_ratio": "0.6",
  "shield": "是",
  "listing_time": "2024-01-03",
},
]

export default DataGoods